version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - readfile-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - readfile-network

networks:
  readfile-network:
    driver: bridge